apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: logstash
  namespace: ela
spec:
  selector:
    matchLabels:
      app: logstash
  template:
    metadata:
      labels:
        app: logstash
    spec:
      containers:
        - name: logstash
          image: docker.elastic.co/logstash/logstash:8.15.3
          securityContext:
            runAsUser: 0
            runAsGroup: 0
            privileged: true
          volumeMounts:
            - name: config
              mountPath: /usr/share/logstash/pipeline/logstash.conf
              subPath: logstash.conf
            - name: host-varlog
              mountPath: /host/var/log
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: logstash-config
        - name: host-varlog
          hostPath:
            path: /var/log
            type: Directory


