apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-config
  namespace: ela
data:
  logstash.conf: |
    input {
      file {
        path => "/host/var/log/messages"
        start_position => "beginning"
        type => "syslog"
      }
    }

    output {
      elasticsearch {
        hosts => ["http://elasticsearch:9200"]
        index => "system-messages-%{+YYYY.MM.dd}"
      }
      stdout { codec => rubydebug }
    }


