apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kibana
  namespace: argocd  # Argo CD が動いている namespace
spec:
  project: default

  source:
    repoURL: https://github.com/takeken-bo/elastic-repo.git
    targetRevision: HEAD
    path: charts/kibana
    helm:
      valueFiles:
        - values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: ela

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

