replicaCount: 1

elasticsearchHosts: "http://elasticsearch:9200"

service:
  type: NodePort
  port: 5601
  nodePort: 30601

ingress:
  enabled: false
    #extraEnvs:
    #  - name: XPACK_SECURITY_ENABLED
    #    value: "false"
env:
  - name: ELASTICSEARCH_HOSTS
    value: "http://elasticsearch:9200"
  - name: XPACK_SECURITY_ENABLED
    value: "false"

