replicaCount: 1

elasticsearchHosts: "http://elasticsearch:9200"

service:
  type: NodePort
  port: 5601
  nodePort: 35601

ingress:
  enabled: false
image:
  repository: localhost:32000/my-kibana
  tag: 8.15.3
  pullPolicy: IfNotPresent
