replicaCount: 1

elasticsearchHosts: "http://elasticsearch:9200"

service:
  type: NodePort
  port: 5601
  nodePort: 30601

ingress:
  enabled: false
    #extraEnvs:
    #  - name: XPACK_SECURITY_ENABLED
    #    value: "false"
kibanaConfig:
  kibana.yml: |
    server.host: "0.0.0.0"
    elasticsearch.hosts: [ "http://elasticsearch:9200" ]
    xpack.security.enabled: false

