apiVersion: v1
kind: ConfigMap
metadata:
  name: elasticsearch-config
  namespace: {{ .Release.Namespace }}
data:
{{- with .Values.esConfig.elasticsearch }}
  elasticsearch.yml: |
{{ . | indent 4 }}
{{- end }}

