apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: elasticsearch-storage-elasticsearch-{{ .Values.nodeIndex }}
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.storage.size }}
  storageClassName: rook-ceph-block

