apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  namespace: ela
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 9200
      protocol: TCP
      name: http
  selector:
    app: elasticsearch

