apiVersion: v1
kind: PersistentVolume
metadata:
  name: elasticsearch-pv1
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: "/mnt/elasticsearch/data1"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: elasticsearch-pv2
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: "/mnt/elasticsearch/data2"

