apiVersion: v1
kind: PersistentVolume
metadata:
  name: elasticsearch-pv0
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/elasticsearch/data0
